package com.goweyy.convoyia.dispatcher.convoy.webhook;

public enum ConvoyWebhookEventType {
    MISSION_DISPATCHED,
    MISSION_VERIFIED,
    MISSION_PRICED,
    MISSION_INSPECTION_PRE_COMPLETED,
    MISSION_INSPECTION_POST_COMPLETED,
    MISSION_ANOMALY_DETECTED,
    MISSION_DAMAGE_DETECTED,
    MISSION_COMPLETED,
    MISSION_FAILED,
    MISSION_ESCALATED
}
