package com.goweyy.convoyia.common.domain.enums;

public enum ConvoyNotificationTemplate {
    MISSION_CONFIRMED,
    DRIVER_ASSIGNED,
    DRIVER_EN_ROUTE,
    MISSION_STARTED,
    ETA_UPDATE,
    MISSION_COMPLETED,
    MISSION_CANCELLED,
    MISSION_RESCHEDULED,
    DAMAGE_DETECTED,
    PAYMENT_CONFIRMED,
    RETURN_BOOKED,
    SURGE_CONFIRMATION_REQUIRED,
    DISPUTE_OPENED,
    DISPUTE_RESOLVED,
    MISSION_UNAVAILABLE
}
