package com.goweyy.convoyia.common.domain.enums;

public enum ConvoyMissionState {
    RECEIVED,
    QUALIFYING,
    ROUTING,
    PENDING_VERIFICATION,
    PENDING_PRICING,
    PENDING_ASSIGNMENT,
    PENDING_BROADCAST,
    PRE_INSPECTION,
    IN_PROGRESS,
    POST_INSPECTION,
    PENDING_BILLING,
    COMPLETED,
    CANCELLED,
    RESCHEDULED,
    UNAVAILABLE,
    FAILED,
    ESCALATED_HUMAN
}
